### ISSUE TITLE
Have educates admin platform delete, delete portal, environment and session resources.

### ISSUE THREAD

**Issue by GrahamDumpleton** [vmware-tanzu-labs/educates-training-platform#209]
### Is your feature request related to a problem? Please describe.

Main docs recommend when deleting training platform that first delete any training portals, workshop environments and sessions etc. This is not done when running the `educates admin platform delete` command. Technically this could result in deleting of training platform being blocked if operators were deleted before workshop environments could be cleaned up.

### Describe the solution you'd like

Have `educates admin platform delete` command first delete at least training portals, waiting for them to delete in foreground. Then possibly also delete workshop environments and sessions in same way. The latter wouldn't be required if training portals always used, but still good thing to do.

**Comment by jorgemoralespou** [comment]
This command will go away with the new installer

**Comment by GrahamDumpleton** [comment]
The commands may go away, but the original problem will still be an issue. That is if delete operators before deleting training portals etc, deletion could hang.
