### ISSUE TITLE
Add REST API endpoint for listing workshops.

### ISSUE THREAD

**Issue by GrahamDumpleton** [vmware-tanzu-labs/educates-training-platform#258]
### Is your feature request related to a problem? Please describe.

One can currently use the REST API to list the workshop environments, where details of the linked workshop is an attribute. I Want the inverse, where you get back a list of the workshops which have an associated running workshop environment as attribute.

### Describe the solution you'd like

Provide REST API endpoint at `.../catalog/workshops/` returning a response like:

```
{
  "portal": {
    "name": "educates-cli",
    "labels": {},
    "uid": "00b141e6-71fb-425c-890f-53af48dfc9dc",
    "generation": 2,
    "url": "https://educates-cli-ui.educates-local-dev.test/",
    "sessions": {
      "maximum": 5,
      "registered": 0,
      "anonymous": 0,
      "allocated": 0
    }
  },
  "workshops": [
    {
      "name": "educates-cli--lab-k8s-fundamentals-999eff2",
      "title": "Kubernetes Fundamentals",
      "description": "An interactive workshop on Kubernetes fundamentals.",
      "vendor": "",
      "authors": [],
      "difficulty": "",
      "duration": "",
      "tags": [],
      "labels": {},
      "logo": "",
      "url": "",
      "environment": {
        "name": "educates-cli-w01",
        "state": "RUNNING",
        "duration": 3600,
        "capacity": 5,
        "reserved": 0,
        "allocated": 0,
        "available": 0
      }
    }
  ]
}
```

Note that it only makes sense to return a workshop where there is a running workshop environment otherwise have to potentially deal with multiple workshops of same name.

Also no need to be able to show active sessions against an environment as that is better handled by existing APIs.

**Comment by jorgemoralespou** [comment]
> Note that it only makes sense to return a workshop where there is a running workshop environment otherwise have to potentially deal with multiple workshops of same name.

What do you mean here? I understand that workshops without an environment are not accesible, and hence probably don't make sense to be returned, but can't really see how there might be conflicting workshop names if what is returned as name is the kubernetes resource name, which is unique.

**Comment by GrahamDumpleton** [comment]
Because you can update a workshop definition, you could have a (or more than one) workshop environment in a stopping state, along with one in running state, for the one workshop name. Would be confusing to return multiple entries in same list with same workshop name but nested details for different workshop environments of different names. So better to return just entry corresponding to workshop environment which is in running state.

**Comment by jorgemoralespou** [comment]
I just realised these REST apis are per training portal, so discard part of my reasoning.
