### ISSUE TITLE
Add CLI command to prune registry.

### ISSUE THREAD

**Issue by GrahamDumpleton** [vmware-tanzu-labs/educates-training-platform#296]
### Is your feature request related to a problem? Please describe.

The local image registry deployed to docker can accumulate unreferenced layers when succesive versions of images are push to the registry using same tag.

### Describe the solution you'd like

Add an `educates admin registry prune` command CLI command which runs:

```
docker exec educates-registry registry garbage-collect /etc/docker/registry/config.yml --delete-untagged=true
```

This mirrors `make prune-registry` command in `Makefile` when doing Educates development.

**Comment by jorgemoralespou** [comment]
This is solved in the new installer
