### ISSUE TITLE
add `base_environment_image` variable

### ISSUE THREAD

**Issue by djschny** [vmware-tanzu-labs/educates-training-platform#306]
### Is your feature request related to a problem? Please describe.

When using an initContainer to do setup work, need to use Educates base image. However the version is not known, so need to manually pick one as opposed it being automatically selected by the version of Educates being run.

### Describe the solution you'd like

Addition of a `base_environment_image` or similar variable that could be used in a workshop definition.

**Comment by GrahamDumpleton** [comment]
Use:

* workshop_image - The image used to deploy the workshop container.
* workshop_image_pull_policy - The image pull policy of the image used to deploy the workshop container.

For variables see:

https://docs.educates.dev/custom-resources/workshop-definition.html#a-note-about-use-of-data-variables

**Comment by djschny** [comment]
Ah OK great, thank you.
