### ISSUE TITLE
`v.2.7.0` says `Update of VS Code editor version to latest available.` but it's not the latest

### ISSUE THREAD

**Issue by djschny** [vmware-tanzu-labs/educates-training-platform#329]
### Describe the bug

Educates v2.7.0 says `Update of VS Code editor version to latest available.` however it appears to use `v4.19.1`. At the time of the release `v4.22.1` was the latest.

**Comment by GrahamDumpleton** [comment]
At the time of the making the change it was the latest. :-)

**Comment by GrahamDumpleton** [comment]
Version 2.7.1 included update to latest version available (VS Code 1.89.1 - code-server v4.89.1) in the few days before release.
