### ISSUE TITLE
Create endpoints for liveness and readiness for the operators

### ISSUE THREAD

**Issue by jorgemoralespou** [vmware-tanzu-labs/educates-training-platform#355]
### Is your feature request related to a problem? Please describe.

When looking at the operators (session-manager, secrets-manager) it would be nice to mark them as ready when it's actually processing work, not during startup time.

### Describe the solution you'd like

Add a liveness and readiness endpoints to both managers so that we can configure them and have kubernetes restart the pods in case any failure is detected from within.

**Comment by GrahamDumpleton** [comment]
Operators already had a liveness check, but did not have a readiness check. For readiness check, can use same existing probe endpoint as used for liveness check.
