### ISSUE TITLE
error with docker for mac on macos 14

### ISSUE THREAD

**Issue by mshahat** [vmware-tanzu-labs/educates-training-platform#365]
### Describe the bug

```
❯ educates create-cluster --with-platform=true --with-services=true
{"status":"Pulling from library/busybox","id":"latest"}
{"status":"Digest: sha256:5eef5ed34e1e1ff0a4ae850395cbf665c4de6b4b83a32a0bc7bcb998e24e7bbb"}
{"status":"Status: Image is up to date for busybox:latest"}
Error: couldn't test whether ports 80/443 available: cannot start busybox container: Error response from daemon: Ports are not available: exposing port TCP 192.168.0.46:443 -> 0.0.0.0:0: failed to connect to /var/run/com.docker.vmnetd.sock: is vmnetd running?: dial unix /var/run/com.docker.vmnetd.sock: connect: no such file or directory
~ ❯  
```

solution is to 

MacOS 14 with Docker Desktop and the CLI works for me.
Can you check if the following setting is enabled?
Docker Desktop > Settings > Advanced > Allow Privileged Port Mapping (requires password)
Maybe that's what's blocking the container from binding to ports < 1024.

ask is to add that to the documentation please. 

Thanks!

**Comment by jorgemoralespou** [comment]
Related to https://github.com/vmware-tanzu-labs/educates-training-platform/issues/253
