### ISSUE TITLE
PSPs and SCCs not being deleted for workshop environment.

### ISSUE THREAD

**Issue by GrahamDumpleton** [vmware-tanzu-labs/educates-training-platform#395]
### Describe the bug

The pod security polices (obsolete Kubernetes versions) and security context constraints (OpenShift) resources created for a workshop environment are not being set as being owned by the workshop namespace. This means these resources are not being deleted automatically when the workshop environment and workshop namespace were deleted.

**Comment by jorgemoralespou** [comment]
I think we should probably remove support for PSPs, since they have been deprecated for long time and those cluster versions are no longer supported.
