### ISSUE TITLE
Shortcut for referring to local image registry and local image builds.

### ISSUE THREAD

**Issue by GrahamDumpleton** [vmware-tanzu-labs/educates-training-platform#416]
### Is your feature request related to a problem? Please describe.

In 2.7.x one used to be able to use a short cut of:

```
educates create-cluster --version=latest
```

and it would internally remap to:

```
--package-repository=localhost:5001 --version=0.0.1
```

You now can't use the short cut and have to supply the latter two options explicitly.

### Describe the solution you'd like

Not sure. Perhaps restore `--version=latest` as a short cut, or perhaps have a separate optional which means to use local registry and build.

Likely affects the `educates create-cluster` command and `educates admin cluster install`. Not sure if other commands affected.

### Additional information

Requirement for later options noted in update build instructions.

* https://github.com/vmware-tanzu-labs/educates-training-platform/blob/develop/developer-docs/build-instructions.md#building-the-educates-cli-program

**Comment by jorgemoralespou** [comment]
I guess, that if convenient, this can be brought back, as this is mostly for development purposes and not likely to affect any end user.
