### ISSUE TITLE
CLI command for fetching config values for installed version of Educates.

### ISSUE THREAD

**Issue by GrahamDumpleton** [vmware-tanzu-labs/educates-training-platform#426]
### Is your feature request related to a problem? Please describe.

The PR https://github.com/vmware-tanzu-labs/educates-training-platform/pull/418 added storing of config values used to deploy Educates platform to the cluster. This is stored in the `educates-config` config map in the `educates-config` namespace. One has to know the specifics for where it is installed to view it.

### Describe the solution you'd like

Add a CLI command for fetching and displaying the config values used to deploy Educates.

```
educates admin platform values
```

or:

```
educates admin platform config
```

Note that for `educates admin config view` command it is a `view` subcommand which displays it, so using `educates admin platform config` alone may be confusing and why suggested maybe `educates admin platform values` instead.

The `educates admin diagnostics collect` command should also capture this config map from the cluster as well.

Note. Should this mask sensitive values such as inline credentials, client IDs, certificates etc and only include them as-is if a specific option is provided.

### Tasks
- [x] Creation of `educates admin platform values` 
- [ ] Adding collection of values to `educates admin diagnostics collect` command

**Comment by jorgemoralespou** [comment]
Part of this is fixed in #461 

Remaining is to add collection of this information to the diagnostics command
