### ISSUE TITLE
New workshop template should list hugo temporary files/directories to a .gitignore file.

### ISSUE THREAD

**Issue by GrahamDumpleton** [vmware-tanzu-labs/educates-training-platform#429]
### Describe the bug

When run Hugo renderer locally with `educates serve-workshop` it leaves a `workshop/.hugo_build.lock` file, plus the `workshop/public` directory which can be accidentally added to a Git repository.

### Additional information

Note these were not supplied in a `.gitignore` file originally since a Git repo wasn't being created and wasn't known whether the generated directory was going to end up as the root of a Git repo or not.

**Comment by jorgemoralespou** [comment]
Even if then this added to top level git, the .gitignore file will still work.
