### ISSUE TITLE
Make --provider option for educates admin services deploy optional.

### ISSUE THREAD

**Issue by GrahamDumpleton** [vmware-tanzu-labs/educates-training-platform#46]
The ``--provider`` flag to ``educates admin services deploy`` is currently required even if value set in config file. Should perhaps be optional if empty doesn't override what is in config file.

**Comment by GrahamDumpleton** [comment]
Currently the `--provider` option is optional for `educates admin platform deploy` and defaults to `kind` which could be problematic.

There needs to be a way to determine the infrastructure provider from the cluster. In the case of local kind cluster created using CLI, it could add a secret/configmap with some details which could be looked up.

**Comment by jorgemoralespou** [comment]
This command will go away with new installer
