### ISSUE TITLE
Contour version deployed by Educates is out of date.

### ISSUE THREAD

**Issue by GrahamDumpleton** [vmware-tanzu-labs/educates-training-platform#54]
Contour was using TCE package bundle but it is no longer updated. The old version being used doesn't seem to work properly on EKS and so Contour needs to be installed separately for that platform before installing Educates.

Need to find alternate source of Contour bundle, or carry our own version of a Carvel package for it and maintain that ourselves.

**Comment by jorgemoralespou** [comment]
This issue will be addressed with the new installer
