### ISSUE TITLE
Always create resources for remote access token.

### ISSUE THREAD

**Issue by GrahamDumpleton** [vmware-tanzu-labs/educates-training-platform#540]
### Is your feature request related to a problem? Please describe.

The remote access token provided to make it easier to generate a `kubeconfig` file for the lookup service, is only pre-created in a cluster when the lookup service is enabled.

### Describe the solution you'd like

I would like the remote access token to always be pre-created, this way it can be relied upon even when the lookup service is not enabled in that cluster, and instead a lookup service in a separate cluster is being used to monitor that cluster.

**Comment by jorgemoralespou** [comment]
If this is not urgent, I'll get to it after my vacation.

**Comment by GrahamDumpleton** [comment]
No rush. Can be done at same time update things so can install lookup service by itself separate to Educates core components, but still with option of contour and other bits etc.
