### ISSUE TITLE
Training portal URL which takes portal password as query string param.

### ISSUE THREAD

**Issue by GrahamDumpleton** [vmware-tanzu-labs/educates-training-platform#87]
### Is your feature request related to a problem? Please describe.

When a portal password is set, as is done automatically when using the `educates` CLI to deploy a workshop or when a portal is created explicitly, you have to use `educates view-credentials` to get the credentials so that when use `educates browse-workshops` you have the password to enter.

It may be better if the fact that the password was required could in part be hidden and be transparent for the local user.

### Describe the solution you'd like

Currently to enter the portal password you need to visit the portal UI and if a password has not already provided, it needs to be supplied via a web form. If the portal could provide a GET URL to facilitate login, where the password is supplied as a query string param, then when using `educates browse-workshops`, it could send the user to the GET URL which takes the password, with it being supplied automatically by the `educates` CLI so the user is automatically logged in.

As well as that, it would be possible to add an `--open-browser` option to `educates deploy-workshop` which would send the user to the portal web site, login them in if needed, with them being left at the list of workshops to select. Technically it could also automatically start an instance of the workshop and that could be done if this option was going to be optional anyway. Note that the `educates CLI` in this case would need to test the URL for the portal first to see if it was ready and that wasn't getting HTTP 404 due to ingress and deployment not being setup yet.

Provided that checking URL works before sending users browser to it, could also provide an `--open-browser` option of `educates create-portal` command.

By making this transparent, the only times a password request would come up would be if a user outside of the machine managed to access the portal somehow; which would have required being able to access it using the correct hostname, and if the user didn't use the `educates` CLI to open the browser and they instead used `kubectl get trainingportals` to work out the URL. In this case they could still use `educates view-credentials` to get the credentials.

**Comment by jorgemoralespou** [comment]
@djschny  Thanks for the tip, but this issue is specific to the experience when you run the educates cli to deploy a workshop which creates an opinionated trainingportal with credentials in it. We have found new users chalkers by this, when working with the platform without big experience or docs reading, so this is basically a convenience for this workflow that AFAIK you don't use.

**Comment by djschny** [comment]
Correct.

FWIW - If i were a new user, I would not want to use a CLI for something like this.

**Comment by GrahamDumpleton** [comment]
Changes made in 2.6.10.
