### ISSUE TITLE
Provide a means to deploy Educates training platform using plain kubectl.

### ISSUE THREAD

**Issue by GrahamDumpleton** [vmware-tanzu-labs/educates-training-platform#89]
### Is your feature request related to a problem? Please describe.

Installation of Educates currently requires Carvel tools on the local host and kapp-controller in the Kubernetes cluster, which is a stumbling block for users if wanting to quickly test it. The `educates` CLI does allow you to quickly create a local Kubernetes cluster, but some may want to test it in a hosted cluster.

### Describe the solution you'd like

Provide a way of deploying core Educates training platform using `kubectl`.

To do this it would be required that the user provide a Kubernetes cluster with a working ingress controller and they still need either a wildcard DNS CNAME configured to point at the cluster, or, know the ingress router IP and can use a `nip.io` address.

Educates should then provide a set of generated resources for deploying just `educates-training-platform`. This would be configured with no cluster or workshop policy engines, so wouldn't be secure, and thus need to state is not secure and not suitable for production environment or for running workshops with untrusted users.

The user will still need to supply an ingress domain so they would need to edit the resources and find the secret containing data values (included in `stringData` form so visible and editable) and change it.

We could also supply a `kustomize` wrapper which can patch the ingress domain (if possible). In the latter case they would use `kubectl apply -k` to install it.

Alternatively we just package all the current `ytt` YAML into a single file, which can then be used with `ytt` with result passed to `kubectl` or `kapp`. This though still means dependent on Carvel tools, but at least do not need `kapp-controller` installed.

In the last case this still couldn't be everything though as Kyervno policies use `_ytt_lib` mechanism. If avoid that, then this would allow overriding of all options, although not sure that data/schema can be part of a larger file, so may not work.

**Comment by jorgemoralespou** [comment]
This is not practical, as it needs ordering. With the new installer, one can install in an imperative manner  (without kapp-controller) as well as declarative with kapp-controller, and also one could generate the yaml to be applied to the cluster, but as ordering is required, you would still need to use kapp for proper ordering of creating the resources.

We close this issue, until we find a better reason to get to it.
